### ISSUE TITLE
Should Pudge's Rot proc Pugna's Nether Ward?

### ISSUE THREAD

**Issue by rafaelcastrocouto** [rafaelcastrocouto/dotacard#1]
Although Pugna is not in the game (yet) ... I would like to know your opinion.

**Comment by ellej16** [comment]
@rafaelcastrocouto Haven't explored the gameplay (or how the skills work differently now), but I'd say no. As Pudge's Rot doesnt use mana

**Comment by rafaelcastrocouto** [comment]
That makes a lot of sense! When I made this issue, the skill cards didn't had the classification that they have now (left and right hands). With the classes, this is easy to understand and implement now because right hand cards use mana and left hand ones don't.

Thanks a lot for the feedback @ellej16 ... plz feel free to make any suggestions or to open new issues!
