### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by ahmetozalp** [rafaelcastrocouto/dotacard#16]
Turkish Language: http://www.ahmetozalp.net/github/katkilar/ui.json

**Comment by rafaelcastrocouto** [comment]
Thanks ... a lot

**Comment by rafaelcastrocouto** [comment]
Why are the characters all messed up? Can you fix it?

https://github.com/rafaelcastrocouto/dotacard/blob/gh-pages/client/json/tr-TR/ui.json

**Comment by ahmetozalp** [comment]
update.

**Comment by rafaelcastrocouto** [comment]
where?

**Comment by ahmetozalp** [comment]
https://github.com/AhmetOZALP/dotacard/blob/patch-2/client/json/tr-TR/ui.json

**Comment by rafaelcastrocouto** [comment]
Thanks a lot! Now it should be working on http://dotacard.ga
