### ISSUE TITLE
Will a new map be added?

### ISSUE THREAD

**Issue by ahmetozalp** [rafaelcastrocouto/dotacard#28]
Will a new map be added?

**Comment by rafaelcastrocouto** [comment]
That would be awesome!
What kind of map? Larger, smaller? Get in the details and share your ideas.

**Comment by ahmetozalp** [comment]
dota 7.00 now playing map :D :dancer:

**Comment by rafaelcastrocouto** [comment]
Do you mean the campaign map? I guess we could make it look like the 7.00 new map, with roshan in the top side if the river and more runes. Is this what you're thinking?

**Comment by rafaelcastrocouto** [comment]
I implemented a new campaign map! Closing this issue ok?
![untitled](https://cloud.githubusercontent.com/assets/422159/21566658/1cd17a36-ce8c-11e6-8c86-6529cf3f5e8d.png)
